auth-server: http://192.168.1.107:9999/uaa

server:
    port: 8886
    context-path: #/liuzh/
eureka:
    instance:
#        appname: business
        instanceId: chapter:chapter_1:a1
        prefer-ip-address: true
    client:
        enabled: true
        healthcheck:
            enabled: true
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://admin:admin@192.168.1.107:8761/eureka/

security:
  # Disable Spring Boot basic authentication
  basic:
    enabled: false
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://${spring.server.path}:${server.port}/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: retailstore
      clientSecret: retailStoreSecret
    resource:
#      user-info-uri: http://${spring.server.path}:${server.port}/uaa/oauth/user
#      token-info-uri: http://${spring.server.path}:${server.port}/uaa/oauth/check_token
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
      id: openid
      serviceId: ${PREFIX:}resource


spring:
    application:
       name: chapter  # Service registers under this name
